runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [ubuntu-latest, windows-latest]
steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-python@v2

  - run: |
    pip install tf-nightly
    python test.py
